name: dlthubsnow
version: 1.0.0
config-version: 2

profile: dlthubsnow

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages", "logs"]

models:
  dlthubsnow:
    curated:
      +materialized: view
