-- Minimal Snowpark Container Services bootstrap for the containerized dlt path.
-- Run this with a role that can create compute pools, network rules, external
-- access integrations, stages, and image repositories.

CREATE DATABASE IF NOT EXISTS DLT_GITHUB_DEMO;
CREATE SCHEMA IF NOT EXISTS DLT_GITHUB_DEMO.PUBLIC;

CREATE COMPUTE POOL IF NOT EXISTS DLT_GITHUB_DEMO_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  AUTO_SUSPEND_SECS = 300;

CREATE IMAGE REPOSITORY IF NOT EXISTS DLT_GITHUB_DEMO.PUBLIC.DLT_GITHUB_REPO;

CREATE STAGE IF NOT EXISTS DLT_GITHUB_DEMO.PUBLIC.DLT_GITHUB_CONTAINER_STAGE
  DIRECTORY = (ENABLE = TRUE);

CREATE OR REPLACE NETWORK RULE DLT_GITHUB_DEMO.PUBLIC.DLT_GITHUB_GH_API_RULE
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('api.github.com');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION DLT_GITHUB_GH_EAI
  ALLOWED_NETWORK_RULES = (DLT_GITHUB_DEMO.PUBLIC.DLT_GITHUB_GH_API_RULE)
  ENABLED = TRUE;

-- No Snowflake destination secret is required for this repo's job container.
-- dlt can use Snowflake's auto-mounted OAuth token inside SPCS when
-- DESTINATION__SNOWFLAKE__CREDENTIALS__AUTHENTICATOR=oauth and the job spec
-- provides the destination database/warehouse.
--
-- Optional for higher GitHub API limits if you add a secret mapping:
--   CREATE OR REPLACE SECRET DLT_GITHUB_TOKEN_SECRET
--     TYPE = GENERIC_STRING
--     SECRET_STRING = '<github-token>';
--
-- The role that executes EXECUTE JOB SERVICE needs at least:
--   USAGE ON DATABASE DLT_GITHUB_DEMO
--   USAGE ON SCHEMA DLT_GITHUB_DEMO.PUBLIC
--   USAGE ON WAREHOUSE DLT_GITHUB_DEMO_WH
--   USAGE ON COMPUTE POOL DLT_GITHUB_DEMO_POOL
--   READ ON IMAGE REPOSITORY DLT_GITHUB_DEMO.PUBLIC.DLT_GITHUB_REPO
--   READ ON STAGE DLT_GITHUB_DEMO.PUBLIC.DLT_GITHUB_CONTAINER_STAGE
--   CREATE SERVICE ON SCHEMA DLT_GITHUB_DEMO.PUBLIC
--   USAGE ON INTEGRATION DLT_GITHUB_GH_EAI
--   USAGE ON SECRET <secret_name> only for any optional secrets you mount
